### ISSUE TITLE
Regression: template with no settings causes errors

### ISSUE THREAD

**Issue by robinhouston** [kiln/flourish-sdk#63]
For example:

```
$ flourish run --no-build --debug
😱  Failed to start server
😱  config.settings is not iterable
😱  TypeError: config.settings is not iterable
    at addShowConditions (/Users/robin/Kiln/flourish/sdk/lib/sdk.js:276:29)
    at readConfig.then.then.config (/Users/robin/Kiln/flourish/sdk/lib/sdk.js:381:19)
```

**Comment by timbrock** [comment]
Looks like I broke it in 3a032c44fb74b673accca46f0d60e75812baff89.

**Comment by robinhouston** [comment]
This will be fixed in the next release. Thanks @timbrock!
